config/routes.rb
Rails.application.routes.draw do

root 'games#new'

resources :games, only: %i[new create update] do
    member do
        get :give_up
        get :challenge
        get :correct
    end
   resource :progresses, only: %i[new create]
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord

  has_many :progresses

end

app/models/progress.rb
class Progress < ApplicationRecord

  belongs_to :game
  belongs_to :question



  def assign_sequence
    next_sequence = 1
    if game.present?
      all_progress = game.progresses
      if all_progress.count > 0
        next_sequence = all_progress.maximum(:sequence) + 1
      end
    end
    self.sequence = next_sequence
  end

  # 質問に対して「はい」と回答したか
  def positive_answer?
    answer == 'positive'
  end
  
  # 質問に対して「いいえ」と回答したか
  def negative_answer?
    answer == 'negative'
  end

end

app/models/question.rb
class Question < ApplicationRecord

  has_many :progresses

  def self.next_question(game)
    answered_question_ids = game.progresses.pluck(:question_id)
    Question.where.not(id: answered_question_ids).shuffle.take(1).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController


  def new
  end

  def create
    game = Game.create!(status: 'in_progress')
    redirect_to new_game_progresses_path(game)
  end

  def challenge
    current_game = Game.find(params[:id])
    extract_comics = ExtractionAlgorithm.new(current_game).compute
    @comic = extract_comics.first
  end

  def give_up

  end

  def update
    current_game = Game.find(params[:id])

    if params[:correct].present?
      current_game.status = 'finished'
      current_game.result = :correct
      current_game.save!

      redirect_to correct_game_path(current_game)
    else
      current_game.status = 'finished'
      current_game.result = :incorrect
      current_game.save!

      redirect_to give_up_game_path(current_game)
    end
  end

  def correct

  end


end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController


  def new
    @progress = Progress.new
    current_game = Game.find(params[:game_id])
    @question = Question.next_question(current_game)
  end

  def create
    current_game = Game.find(params[:game_id])
    # 回答した内容を保存する
    progress = current_game.progresses.new(create_params)
    progress.assign_sequence
    progress.save!
    # 絞り込みを実行
    @extract_comics = ExtractionAlgorithm.new(current_game).compute

    # 絞り込み結果が0件の場合、ギブアップ画面へ遷移
    if @extract_comics.count == 0
      redirect_to give_up_game_path(current_game)
      return
    end

    # 絞り込み結果が1件の場合、チャレンジ(正解を当てにいく)へ遷移
    if @extract_comics.count == 1
      redirect_to challenge_game_path(current_game)
      return
    end

    next_question = Question.next_question(current_game)
    if next_question.blank?
      current_game.status = 'finished'
      current_game.result = 'incorrect'
      current_game.save!
      redirect_to give_up_game_path(current_game)
      return
    end

    redirect_to new_game_progresses_path(current_game)
  end

  private

  def create_params
    params.require(:progress).permit(:question_id, :answer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/comics/_list.htrml.erb
<div id = "comics_list">
  <p>
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample">
      漫画候補一覧はこちら
    </button>
  </p>
  <div class="collapse" id="collapseExample">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">タイトル</th>
        <th scope="col">ジャンル</th>
        <th scope="col">連載</th>
        <th scope="col">連載期間</th>
      </tr>
      </thead>
      <tbody>
      <% Comic.all.each do | comic | %>
        <tr>
          <td><%= comic.title %></td>
          <td><%= comic.genre %></td>
          <td><%= comic.publisher %></td>
          <td><%= comic.serialization_started_year %> ~ <%= comic.serialization_end_year %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/games/challenge.html.erb
<div id="main">
  <%= form_with url: game_path, method: :patch, local:true do |f| %>

    <div class="row">
      <div class="col-12">
        <div class="card bg-light">
          <div class="card-header">あなたがイメージした漫画はこれですね？</div>
          <div class="card-body">
            <p class="card-text"><%= @comic.title %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row mt-5">
      <div class="col-6">
        <%= f.submit("違います", name: :incorrect, class: "btn btn-lg btn btn-outline-info btn-block") %>
      </div>
      <div class="col-6">
        <%= f.submit("正解です", name: :correct, class: "btn btn-lg btn btn-outline-info btn-block") %>
      </div>
    </div>
<% end %>
</div>

app/views/games/correct.html.erb
<div id="main">

  <div class="form-group row">
    <div class="col-12">
      <div class="card bg-light">
        <div class="card-body">
          <p class="card-text">当たりました！</br>もう一度やりますか？</p>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row mt-5">
    <div class="col-12">
      <%= link_to("もう一度ゲームする", root_path, class: "btn btn-lg btn btn-outline-info btn-block")  %>
    </div>
  </div>
</div>

app/views/games/give_up.html.erb
<div id="main">
  <div class="form-group row">
    <div class="col-12">
      <div class="card bg-light">
        <div class="card-body">
          <p class="card-text">参りました。わかりませんでした。</br>もう一度やりますか？</p>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row mt-5">
    <div class="col-12">
      <%= link_to("もう一度ゲームする", root_path, class: "btn btn-lg btn btn-outline-info btn-block")  %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div id="main">
  <div class="row mt-3">
    <div class="col-12">
      あなたが思った漫画を当ててみせましょう！<br/>
      下記漫画から一つを頭に思い描いてください。<br/>
      準備ができたらゲームを始めてください。
    </div>
  </div>
  <%#= render "comics/list" %>

  <div id = "comics_list">
    <p>
      <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample">
        漫画候補一覧はこちら
      </button>
    </p>
    <div class="collapse" id="collapseExample">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">タイトル</th>
            <th scope="col">ジャンル</th>
            <th scope="col">連載</th>
            <th scope="col">連載期間</th>
          </tr>
        </thead>
        <tbody>
          <% Comic.all.each do | comic | %>
            <tr>
              <td><%= comic.title %></td>
              <td><%= comic.genre %></td>
              <td><%= comic.publisher %></td>
              <td><%= comic.serialization_started_year %> ~ <%= comic.serialization_end_year %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= form_with url: games_path, local:true do |f| %>
    <div class="row mt-3">
      <div class="col-6 offset-3">
        <%= f.submit "はじめる", {class: 'btn btn-lg btn-primary btn-block'} %>
      </div>
   </div>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Techpitnator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container text-center">

      <header class="row mb-3">
        <div class="col-12">
          <%= image_tag 'title.png', {width: 200} %>
          <br>
          <%= image_tag 'techpitnator.png', {width: 200} %>
        </div>
      </header>

      <main class="row">
        <div class="col-8 offset-2">
          <%= yield %>
        </div>
      </main>

    </div>
  </body>
</html>

app/views/progresses/new.html.erb
<div id="main">
  <div class="row">
    <div class="col-12">
      <div class="card bg-light">
        <div class="card-header">質問</div>
        <div class="card-body">
          <p class="card-text"><%= @question.content %></p>
        </div>
      </div>
    </div>
  </div>

  <%= form_with model: @progress, url: game_progresses_path, local:true do |f| %>
    <%= f.hidden_field :question_id, :value => @question.id %>
    <div class="row mt-5">
      <div class="col-12">
        <div class="form-check form-check-inline mr-5">
          <%= f.radio_button :answer, :positive, {class: "form-check-input"} %>
          <%= f.label :answer_positive, "はい", {class: "form-check-label"} %>
        </div>
        <div class="form-check form-check-inline mr-5">
          <%= f.radio_button :answer, :unknown, {class: "form-check-input"} %>
          <%= f.label :answer_unknown, "わからない", {class: "form-check-label"} %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :answer, :negative, {class: "form-check-input"} %>
          <%= f.label :answer_negative, "いいえ", {class: "form-check-label"} %>
        </div>
      </div>
    </div>

    <div class="row mt-5">
      <div class="col-6 offset-3">
        <%= f.submit("回答を送信", class:"btn btn-lg btn btn-outline-info btn-block") %>
      </div>
    </div>
  <% end %>
</div>